server {
  listen 80 http2;
  server_name _;
  
	root /app;
	index index.html;

	location / {
			try_files $uri $uri/ /index.html;
	}

	# Optional: better caching for static assets
	location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|webp)$ {
			expires 1y;
			access_log off;
			add_header Cache-Control "public";
	}

	error_page 404 /index.html;
}